backend/app/controllers/post_controllers.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.domain.services.post_service import PostService
from datetime import datetime

bp = Blueprint('post', __name__)

@bp.route('/posts', methods=['GET'])
def get_posts():
    posts = PostService.get_all_posts()
    return render_template('posts.html', posts=posts)

@bp.route('/newPost', methods=['GET', 'POST'])
def create_post():
    if request.method == 'POST':
        try:
            content = request.form['content']
            user_id = request.form['user_id']  # Assuming you have a way to determine the author

            # Call the PostService to create a new post
            PostService.create_post(
                content=content,
                user_id=user_id
            )

            return redirect(url_for('post.get_posts'))  # Redirect after creating the post

        except Exception as e:
            return render_template('new_post.html', error=f'An error occurred: {e}')
    
    # If GET, just show the form
    return render_template('new_post.html')

backend/app/controllers/user_controller.py
from flask import Blueprint, render_template, request , redirect, url_for, flash
from app.domain.services.user_service import UserService
from datetime import datetime
from werkzeug.security import check_password_hash
bp = Blueprint('user', __name__)

@bp.route('/users', methods=['GET'])
def get_users():
    users = UserService.get_all_users()
    return render_template('users.html', users=users)

def is_valid_gmail(email):
    import re
    pattern = r'^[a-zA-Z0-9._%+-]+@gmail\.com$'
    return re.match(pattern, email) is not None

@bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        try:
            username = request.form['username']
            first_name = request.form['first_name']
            last_name = request.form['last_name']
            birth_date = datetime.strptime(request.form['birth_date'], '%Y-%m-%d')
            phone_number = request.form.get('phone_number')
            gender = request.form.get('gender')
            email = request.form['email']
            password = request.form['password']

            UserService.create_user(
                username=username,
                first_name=first_name,
                last_name=last_name,
                birth_date=birth_date,
                phone_number=phone_number,
                gender=gender,
                email=email,
                password=password
            )
            return redirect(url_for('user.get_users'))  # Redirige después de crear el usuario

        except Exception as e:
            return render_template('register.html', error=f'Ocurrió un error: {e}')
    
    # Si es GET, simplemente muestra el formulario
    return render_template('register.html')


@bp.route('/update/<int:user_id>', methods=['GET', 'POST'])
def actualizar_usuario(user_id):
    if request.method == 'POST':
        try:
            username = request.form.get('username')
            first_name = request.form.get('first_name')
            last_name = request.form.get('last_name')
            birth_date_str = request.form.get('birth_date')
            phone_number = request.form.get('phone_number')
            gender = request.form.get('gender')
            email = request.form.get('email')
            password = request.form.get('password')

            try:
                birth_date = datetime.strptime(birth_date_str, '%Y-%m-%d').date()
            except (ValueError, TypeError):
                return render_template('actualizar_perfil.html', error='Formato de fecha inválido.', user_id=user_id)

            result = UserService.update_user(
                user_id=user_id,
                username=username,
                first_name=first_name,
                last_name=last_name,
                birth_date=birth_date,
                phone_number=phone_number,
                gender=gender,
                email=email,
                password=password
            )

            if isinstance(result, dict) and 'error' in result:
                return render_template('actualizar_perfil.html', error=result['error'], user_id=user_id)

            return redirect(url_for('user.get_users'))

        except Exception as e:
            return render_template('actualizar_perfil.html', error=f'Ocurrió un error: {e}', user_id=user_id)

    user = UserService.get_user_by_id(user_id)
    if user:
        return render_template('actualizar_perfil.html', user=user)
    else:
        return render_template('actualizar_perfil.html', error='Usuario no encontrado.', user_id=user_id)
    
@bp.route('/login', methods=['GET', 'POST'])
def login():
    message = None
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = UserService.authenticate_user(username, password)
        if user:
            message = '¡Felicidades! Has iniciado sesión correctamente.'
        else:
            message = 'Nombre de usuario o contraseña incorrectos.'
    return render_template('login.html', message=message)

backend/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask App</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <div class="container">
        {% block content %}
        <!-- Contenido de las páginas específicas -->
        {% endblock %}
    </div>
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
</body>
</html>

backend/app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to Flask App</h1>
    <button>Click Me!</button>
{% endblock %}

backend/app/templates/new_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Post</title>
</head>
<body>
    <h1>Create New Post</h1>
    {% if error %}
        <p style="color:red;">{{ error }}</p>
    {% endif %}
    <form action="{{ url_for('post.create_post') }}" method="post">
        <label for="content">Content:</label>
        <textarea name="content" id="content" required></textarea><br>
        
        <label for="author_id">Author ID:</label>
        <input type="number" name="author_id" id="author_id" required><br>
        
        <button type="submit">Submit</button>
    </form>
    <a href="{{ url_for('post.get_posts') }}">Back to Posts</a>
</body>
</html>

backend/app/templates/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Posts</title>
</head>
<body>
    <h1>Posts</h1>
    <ul>
        {% for post in posts %}
            <li>{{ post.content }} by {{ post.author_id }} at {{ post.timestamp }}</li>
        {% endfor %}
    </ul>
    <a href="{{ url_for('post.create_post') }}">Create New Post</a>
</body>
</html>

backend/app/templates/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Crear Usuario</title>
</head>
<body>
    <h1>Crear Usuario</h1>
    <form action="/registrar_usuario" method="post">
        <label for="username">Nombre de usuario:</label><br>
        <input type="text" id="username" name="username" required><br><br>

        <label for="first_name">Nombre:</label><br>
        <input type="text" id="first_name" name="first_name" required><br><br>

        <label for="last_name">Apellido:</label><br>
        <input type="text" id="last_name" name="last_name" required><br><br>

        <label for="birth_date">Fecha de nacimiento:</label><br>
        <input type="date" id="birth_date" name="birth_date" required><br><br>

        <label for="phone_number">Número de teléfono:</label><br>
        <input type="text" id="phone_number" name="phone_number"><br><br>

        <label for="gender">Género:</label><br>
        <input type="text" id="gender" name="gender"><br><br>

        <label for="email">Correo electrónico:</label><br>
        <input type="email" id="email" name="email" required><br><br>

        <label for="password">Contraseña:</label><br>
        <input type="password" id="password" name="password" required><br><br>

        <input type="submit" value="Crear Usuario">
    </form>


    {% if error %}
        <p style="color:red;">{{ error }}</p>
    {% endif %}

    <a href="{{ url_for('user.get_users') }}">Ver Usuarios</a>
    
</body>
</html>

backend/app/templates/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users</title>
</head>
<body>
    <h1>Users</h1>
    <ul>
        {% for user in users %}
            <li>{{ user.username }} ({{ user.email }})</li>
        {% endfor %}
    </ul>
</body>
</html>